@startuml caso de uso nivel 0

actor Jugador

package "Registro de usuario" {
    
    usecase "Crear entrenador" as creEnt
    usecase "Elegir género" as eleGen
    usecase "Elegir nombre" as eleNom

    usecase "Iniciar torneo" as iniTor
    usecase "Registrarse en el torneo" as resTor
    Jugador -- iniTor
    iniTor ..> resTor: <<include>> 

    creEnt ..> eleGen: <<include>>
    creEnt ..> eleNom: <<include>>
    
}

package "Batallas Pookémon" {
    
    usecase "Iniciar batalla" as iniBat
    usecase "Recibir Pookémones" as recPoo

    usecase "Ver estadisticas de Pookémones" as verEst
    usecase "Atacar oponente" as ataOpo
    usecase "Defenderse de oponente" as defOpo
    usecase "Aplicar objeto" as aplObj
    usecase "Cambiar Pookémon" as camPoo
    usecase "Rendirse" as ren

    iniBat <.. iniTor: <<include>>
    resTor ..> creEnt: <<include>>
    
    verEst .> iniBat: <<extend>>
    ataOpo ..> iniBat: <<extend>>
    defOpo ...> iniBat: <<extend>>
    aplObj ..> iniBat: <<extend>>
    camPoo ..> iniBat: <<extend>>
    ren ...> iniBat: <<extend>>

    iniBat ..> recPoo: <<include>>
    
}
@enduml
