@startuml diagrama de clases

left to right direction

    class Organizador {
        - idOrganizador : int
        - torneoActual : Torneo
        - password : String

        + inscribirJugadorTorneo(jugador : Entrenador, idTorneo: int)
        + torneoPorID(idTorneo : int)
        + agregarPookemon(pookemon : Pookemon)
        + editarPookemon(idPookemon : int, nombrePookemon : String, nombreElemento : String, efect: Efecto)
        + eliminarPookemon(idPookemon : int)
        + agregarMovimiento(mov : Movimiento)
        + editarMovimiento(idMov : int, nombreMovimiento : String, daño : int, precision : int, velocidad : int)
        + eliminarMovimiento(idMovimiento : int)
        + crearTorneo()

        + definirRecompensa(idTorneo : int, recompensa : str)
        + mostrarReporteBatalla(idTorneo : int, idBatalla : int)   
        + mostrarCreditos()
    }

    newpage

    class Entrenador {
        - idEntrenador : int
        - nombreEntrenador : str
        - generoEntrenador : str
        - pokemonActual : int 
        - premios : ArrayList<Recompensa>

        + defenderse()
        + atacar(idMovimiento : int, objetivo : Pookemon)
        + usarObjeto(idObjeto : int)
        + usarObjeto(idObjeto : int, idMovimiento : int)
        + cambiarPookemon(idPookemon : int)
        + obtenerPookemonPorID(idPookemon : int)
        
    }

    newpage

    class Objeto{
        - idObjeto : int
        - nombreObjeto  : str
        - tipoObjeto : str
        - puntosR : int

        + usarObjeto(pookemon : Pookemon)
        + usarObjeto(pookemon : Pookemon, idMovimiento : int)
    }

    newpage

    class Pookemon {
        - idPookemon : int
        - nombrePookemon : str
        - elementoPookemon : str
        - estadisticaPookemon : Estadistica
        - movimientos : ArrayList<Movimiento>
        - efecto : Efecto
        - defendiendo : boolean
        
        + activarDefensa()
        + afectarHp()
        + obtenerMovimientoPorID(idMovimiento : int)
    }

    newpage

    class Estadistica {
        - vida : int 
        - ataqueFisico : int
        - defensaFisica : int
        - ataqueEspecial : int 
        - defensaEspecial : int
        - velocidad : int 

        + toString()
  }

    newpage

    class Movimiento {
        - idMovimiento : int
        - nombreMovimiento: str
        - descripcionMovimiento : str
        - potencia : int
        - precision: int
        - cantidadPP : int
        - elemento : str
        - efecto : Efecto
        - tablaEfectividad: Map<String, Map<String,double>> 

        # calcularDañoBase(atacante: Pookemon, defensor: Pookemon)
        - calcularGolpeCritico()
        - calcularEfectividad(defensor: Pookemon)
        - calcularAumentoPorAfinidadDeElemento(atacante: Pookemon)
        + calcularDañoTotal(atacante: Pookemon, defensor: Pookemon)
        + realizar(atacante: Pookemon, defensor: Pookemon)
        - inicializarTablaEfectividad()
    }

    newpage

    class MovimientoFisico{
        # calcularDañoBase(atacante: Pookemon, defensor: Pookemon)
    }

    newpage 

    class MovimientoEspecial{
        # calcularDañoBase(atacante: Pookemon, defensor: Pookemon)
    } 

    newpage

    class Batalla {
        - idBatalla : int
        - entrenador1 : Entrenador
        - entrenador2 : Entrenador
        - turnos: ArrayList<String>
        - numeroTurno: int

        + iniciarBatalla()
        + generarMazoPookemones()
        + aplicarEfectosPersistentes()
        + determinarTurno()
        + ejecutarTurno(Primero : Entrenador, Segundo : Entrenador)
        + generarReporteBatalla()
        
    }

    newpage

    class NodoTorneo {
      - nodoTorneoIzq: NodoTorneo
      - nodoTorneoDer: NodoTorneo
      - batalla : Batalla
      - ganador : Entrenador 

      + determinarGanador()

    }

    newpage

    class Torneo {
        - recompensa :  Recompensa
        - ganador : NodoTorneo

        + toStringJugadores()
        + toStringPookemones()

        + gestionarRondasTorneo()
        + iniciarTorneo()
        + getGanador()  
    }

    note right of Torneo::gestionarRondasTorneo
        método que vaya posicionando el ganador 
        de cada nodo en el nodo anterior 
        (siguiendo secuencia de árbol)
    end note

    newpage

    class Recompensa {
        - idRecompensa : int
        - nombre : str
        - description : str
        - fechaVencimiento : str 

        + generarCodigo()

    }

    newpage 
    
    


@enduml   
    

    

    
