@startuml casos_de_uso_nivel_0

left to right direction

actor Jugador 
actor Organizador 

package "pookemon.software" {
    
    usecase "Registrar en la Batalla" as regTor
    usecase "Crear Entrenador" as creEnt
    usecase "Participar en Batalla" as parBat

    usecase "Ver creditos" as verCre

    usecase "Gestionar arena" as creTor
    usecase "Ingresar contraseña" as ing
  
}

Jugador -- verCre


Jugador -- regTor
regTor ..> creEnt:<<include>>
regTor ..> parBat:<<include>>

Organizador --- verCre
Organizador -- ing

ing <.. creTor:<<extend>>


@enduml
