@startuml casos_de_uso_nivel_0

left to right direction

actor Jugador 
actor Organizador 

package "pookemon.software" {
    
    usecase "Registrarse en el Torneo" as regTor
    usecase "Crear Entrenador" as creEnt
    usecase "Participar en Batalla" as parBat

    usecase "Ver creditos" as verCre

    usecase "Crear Torneo" as creTor
    usecase "Hacer Seguimiento al Torneo" as hacSeg
    usecase "Definir Recompensa del ganador" as defRec
    usecase "Gestionar Pookemones" as gesPoo
    usecase "Gestionar Movimientos" as gesMov
    usecase "Gestionar Entrenadores" as gesEnt
    usecase "Gestionar Objetos" as gesObj
}

Jugador -- verCre


Jugador -- regTor
regTor ..> creEnt:<<include>>
regTor <.. parBat:<<extend>>

Organizador --- verCre

Organizador -- creTor
creTor .> defRec:<<include>>
creTor <.. gesEnt:<<extend>>
creTor <.. hacSeg:<<extend>>


Organizador -- gesPoo
Organizador -- gesObj
Organizador -- gesMov

@enduml
