@startuml Jugador

left to right direction

actor Jugador

package participar_en_batalla{
    usecase "Luchar" as luc
    usecase "Defender" as def
    usecase "Cambiar" as cam 
    usecase "Objeto" as obj
    usecase "Elegir movimiento a usar" as eleMov
    usecase "Elegir pookemon a cambiar" as elePoo
    usecase "Elegir objeto a usar" as eleObj
    usecase "Ir hacia atrás" as back
}

Jugador -- obj
obj <.. eleObj: <<extends>>
Jugador -- cam
cam <.. elePoo : <<extends>>
Jugador -- luc
luc <.. eleMov : <<extends>>
Jugador -- def
Jugador -- back

package crear_entrenador{
    usecase "Elegir nombre" as eleNom
    usecase "Elegir genero" as eleGen
}

Jugador -- eleNom
Jugador -- eleGen

@enduml