@startuml Organizador

left to right direction

actor Organizador

package gestionar_pookemones{
    usecase "Agregar pookemon" as agrPoo
    usecase "Asignar estadisticas" as asiEst
    usecase "Asignar imagen" as asiImag 
    usecase "Eliminar pookemon" as eliPoo
    usecase "Editar pookemon" as ediPoo
}

Organizador -- agrPoo
agrPoo ..> asiEst: <<include>>
agrPoo ..> asiImag: <<include>>
Organizador -- ediPoo
Organizador -- eliPoo

package gestionar_movimientos{
    usecase "Agregar movimiento" as agrMov
    usecase "Crear movimiento" as creMov
    usecase "Editar movimiento" as ediMov
}

Organizador -- agrMov
Organizador -- creMov
Organizador -- ediMov


package gestionar_batalla{
    usecase "Listar movimientos" as lisMov
    usecase "Listar Pookemones" as lisPoo
}

Organizador -- lisMov
Organizador -- lisPoo

@enduml