@startuml Organizador

actor Organizador

package gestionar_pookemones{
    usecase "Agregar pookemon" as agrPoo
    usecase "Asignar estadisticas" as asiEst
    usecase "Asignar movimientos" as asiMov
    usecase "Crear movimientos" as creMov
    usecase "Eliminar pookemon" as eliPoo
}

Organizador -- agrPoo
agrPoo ..> asiEst: <<include>>
agrPoo ..> asiMov: <<include>>
agrPoo ..> creMov: <<extends>>
Organizador -- eliPoo

package gestionar_premios{
    usecase "Crear premios" as crePre
    usecase "Asignar premio al torneo" as asiPreTor
    usecase "Eliminar premios" as eliPre
}

usecase "Consultar reportes de batalla" as verHisBat

Organizador -- crePre
crePre ..> asiPreTor: <<include>>
Organizador -- eliPre
Organizador -- verHisBat

@enduml