@startuml caso de uso nivel 0

left to right direction

actor Jugador 
actor Administrador

package "menu principal"{

    usecase "gestionar entrenador" as gesEnt

    usecase "gestionar premios" as gesPre
    usecase "gestionar torneo" as gesTor
    usecase "gestionar Arbitros" as gesArb

    usecase "gestionar batallas" as gesBat
    usecase "gestionar jugadores" as gesJug
    usecase "gestionar pookemones" as gesPoo
    usecase "gestionar objetos" as gesObj

}

Jugador -- gesEnt

Administrador -- gesTor
gesTor <.. gesPre:<<extend>>
gesTor <.. gesArb:<<extend>>

Administrador -- gesBat
gesBat ..> gesJug:<<include>>
Administrador -- gesPoo
Administrador -- gesObj

@enduml