/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main.java.com.pml.appPookemon.gui;

import main.java.com.pml.appPookemon.gui.jugador.ListoPanel;
import main.java.com.pml.appPookemon.gui.admin.AdminPanel;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.List;
import java.util.Stack;
import javax.swing.JOptionPane;
import main.java.com.pml.appPookemon.gui.admin.NumPartPanel;
import main.java.com.pml.appPookemon.gui.jugador.RegistroPanel;

/**
 *
 * @author eddie
 */
public class MainFrame extends javax.swing.JFrame {

    private CardLayout cardLayout;
    private Stack<String> panelHistory;
    private List<RegistroPanel> registros;
    /**
     * Creates new form Main
     */
    public MainFrame() {
        panelHistory = new Stack<>();
        initComponents();
        setupPanels();
    }
    
    private void setupPanels() {
        // Creamos el CardLayout
        cardLayout = new CardLayout();
        getContentPane().setLayout(cardLayout);

        // Instanciar los paneles
        WelcomePanel WelcomeP = new WelcomePanel(this);
        AdminPanel adminP = new AdminPanel(this);
        NumPartPanel numPartP = new NumPartPanel(this);
        registros = new ArrayList<>();
        ListoPanel listoP = new ListoPanel(this);

        // Agregamos los paneles al CardLayout
        getContentPane().add(WelcomeP, "welcomeP");
        getContentPane().add(adminP, "adminP");
        getContentPane().add(numPartP, "numPartP");
        getContentPane().add(listoP, "listoP");
        
        // Mostrar el primer panel por defecto
        switchToWelcomePanel();
    }

    // Método para cambiar entre paneles
    private void switchPanel(String panelName) {
        cardLayout.show(getContentPane(), panelName);
        panelHistory.push(panelName);
    }

    public void switchToWelcomePanel() {
        switchPanel("welcomeP");
    }
    public void switchToAdminPanel() {
        switchPanel("adminP");
    }
    public void switchToNumeroPartPanel() {
        switchPanel("numPartP");
    }
     public void switchToListoPanel() {
        switchPanel("listoP");
    }
    public void switchToRegistroPanel(int indice) {
        if (indice < registros.size()) {
            switchPanel("regP" +indice);
        } else {
            switchToListoPanel();
        }    
    }
    
    public void createRegistroPanels(int num) {
        for (int i = 0; i < num; i++) {
            RegistroPanel regP = new RegistroPanel(this,i+1);
            registros.add(regP);
            getContentPane().add(regP, "regP" + i);
        }
    }

    // Método para volver al último panel
    public void goBack() {
        if (panelHistory.size() > 1) { 
            panelHistory.pop();
            String previousPanel = panelHistory.peek(); 
            cardLayout.show(getContentPane(), previousPanel);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        MnMenu = new javax.swing.JMenu();
        MniAtras = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MnMenu.setText("Menu");
        MnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnMenuActionPerformed(evt);
            }
        });

        MniAtras.setText("volver");
        MniAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MniAtrasActionPerformed(evt);
            }
        });
        MnMenu.add(MniAtras);

        jMenuBar1.add(MnMenu);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 424, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnMenuActionPerformed
       
    }//GEN-LAST:event_MnMenuActionPerformed

    private void MniAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MniAtrasActionPerformed
        goBack();
    }//GEN-LAST:event_MniAtrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MnMenu;
    private javax.swing.JMenuItem MniAtras;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
