/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main.java.com.pml.appPookemon.gui.admin;

import javax.swing.JOptionPane;
import main.java.com.pml.appPookemon.datos.pookemon.model.Movimiento;
import main.java.com.pml.appPookemon.datos.pookemon.model.Pookemon;
import main.java.com.pml.appPookemon.datos.torneo.controller.TorneoController;
import main.java.com.pml.appPookemon.gui.MainFrame;
import main.java.com.pml.appPookemon.gui.config.StandarPanel;
import org.jdesktop.swingx.prompt.PromptSupport;

/**
 *
 * @author eddie
 */
public class EditarPanel extends StandarPanel {

    private String nombre;
    private String nombreBuscado;
    private Pookemon pookemonBuscado;
    private Movimiento movimientoBuscado;
    TorneoController torneo = super.getMainFrame().getController();
    /**
     * Creates new form EditarPanel
     */
    public EditarPanel(MainFrame mainFrame) {    
        super(mainFrame);
        initComponents();
    }
    
    public void configurarContenido(){
        String lb = "Editar: "+" "+nombre;
        lbEditar.setText(lb);
        PromptSupport.setPrompt("NOMBRE DEL "+nombre, txtBuscar);
        if(nombre.equalsIgnoreCase("pookemon")){
            configurarParaPookemon();
        }else{
            configurarParaMovimiento();
        }
    }
    
    private void configurarParaPookemon() {
        setVisField(true);
        lbOldCampo1.setText("VIDA:");
        lbOldCampo2.setText("ATQ. FISICO:");
        lbOldCampo3.setText("DEF. FISICA:");
        lbOldCampo4.setText("ATQ. ESPECIAL:");
        lbOldCampo5.setText("DEF. ESPECIAL:");
        lbOldCampo6.setText("VELOCIDAD:");
        lbNewCampo1.setText("VIDA:");
        lbNewCampo2.setText("ATQ. FISICO:");
        lbNewCampo3.setText("DEF. FISICA:");
        lbNewCampo4.setText("ATQ. ESPECIAL:");
        lbNewCampo5.setText("DEF. ESPECIAL:");
        lbNewCampo6.setText("VELOCIDAD:");
    }
    
    private void configurarParaMovimiento() {
        lbOldCampo1.setText("DETALLE:");
        lbOldCampo2.setText("POTENCIA:");
        lbOldCampo3.setText("PRECISIÓN:");
        lbOldCampo4.setText("CANTIDAD PP'S:");
        lbNewCampo1.setText("DETALLE:");
        lbNewCampo2.setText("POTENCIA:");
        lbNewCampo3.setText("PRECISIÓN:");
        lbNewCampo4.setText("CANTIDAD PP'S:");
        setVisField(false);
    }
    private void setVisField(boolean value){
        lbOldCampo5.setVisible(value);
        txtOldCampo5.setVisible(value);
        lbOldCampo6.setVisible(value);
        txtOldCampo6.setVisible(value);
        lbNewCampo5.setVisible(value);
        txtNewCampo5.setVisible(value);
        lbNewCampo6.setVisible(value);
        txtNewCampo6.setVisible(value);
    }

    public void clearFields() {
        txtOldCampo1.setText("");
        txtOldCampo2.setText("");
        txtOldCampo3.setText("");
        txtOldCampo4.setText("");
        txtOldCampo5.setText("");
        txtOldCampo6.setText("");
        txtNewCampo1.setText("");
        txtNewCampo2.setText("");
        txtNewCampo3.setText("");
        txtNewCampo4.setText("");
        txtNewCampo5.setText("");
        txtNewCampo6.setText("");
        txtBuscar.setText("");
    }

    
    public void setNombre(String nombre){
        this.nombre = nombre;
    }
    public String getNombre(){
        return nombre;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings(value = "unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbEditar = new javax.swing.JLabel();
        btActualizar = new javax.swing.JButton();
        jpOld = new javax.swing.JPanel();
        lbOldCampo1 = new javax.swing.JLabel();
        lbOldCampo2 = new javax.swing.JLabel();
        lbOldCampo3 = new javax.swing.JLabel();
        lbOldCampo4 = new javax.swing.JLabel();
        lbOldCampo5 = new javax.swing.JLabel();
        lbOldCampo6 = new javax.swing.JLabel();
        lbOldNombre = new javax.swing.JLabel();
        txtOldCampo1 = new javax.swing.JTextField();
        txtOldCampo2 = new javax.swing.JTextField();
        txtOldCampo3 = new javax.swing.JTextField();
        txtOldCampo4 = new javax.swing.JTextField();
        txtOldCampo5 = new javax.swing.JTextField();
        txtOldCampo6 = new javax.swing.JTextField();
        jpNew = new javax.swing.JPanel();
        lbNewCampo1 = new javax.swing.JLabel();
        lbNewCampo2 = new javax.swing.JLabel();
        lbNewCampo3 = new javax.swing.JLabel();
        lbNewCampo4 = new javax.swing.JLabel();
        lbNewCampo5 = new javax.swing.JLabel();
        lbNewCampo6 = new javax.swing.JLabel();
        lbNewNombre = new javax.swing.JLabel();
        txtNewCampo1 = new javax.swing.JTextField();
        txtNewCampo2 = new javax.swing.JTextField();
        txtNewCampo3 = new javax.swing.JTextField();
        txtNewCampo4 = new javax.swing.JTextField();
        txtNewCampo5 = new javax.swing.JTextField();
        txtNewCampo6 = new javax.swing.JTextField();
        btBuscar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        lbEditar.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        lbEditar.setText("Editar: ");

        btActualizar.setText("Actualizar");
        btActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btActualizarActionPerformed(evt);
            }
        });

        jpOld.setBackground(new java.awt.Color(204, 204, 204));

        lbOldCampo1.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        lbOldCampo1.setText("campo1:");

        lbOldCampo2.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        lbOldCampo2.setText("campo2:");

        lbOldCampo3.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        lbOldCampo3.setText("campo3:");

        lbOldCampo4.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        lbOldCampo4.setText("campo4:");

        lbOldCampo5.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        lbOldCampo5.setText("campo5:");

        lbOldCampo6.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        lbOldCampo6.setText("campo6:");

        lbOldNombre.setFont(new java.awt.Font("sansserif", 3, 15)); // NOI18N
        lbOldNombre.setText("Nombre id");

        txtOldCampo1.setEditable(false);
        txtOldCampo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOldCampo1ActionPerformed(evt);
            }
        });

        txtOldCampo2.setEditable(false);

        txtOldCampo3.setEditable(false);
        txtOldCampo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOldCampo3ActionPerformed(evt);
            }
        });

        txtOldCampo4.setEditable(false);

        txtOldCampo5.setEditable(false);

        txtOldCampo6.setEditable(false);

        javax.swing.GroupLayout jpOldLayout = new javax.swing.GroupLayout(jpOld);
        jpOld.setLayout(jpOldLayout);
        jpOldLayout.setHorizontalGroup(
            jpOldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpOldLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jpOldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbOldCampo2)
                    .addComponent(lbOldCampo1)
                    .addComponent(lbOldCampo3)
                    .addComponent(lbOldCampo4)
                    .addComponent(lbOldCampo5)
                    .addComponent(lbOldCampo6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpOldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbOldNombre)
                    .addComponent(txtOldCampo2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtOldCampo1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtOldCampo3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtOldCampo4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtOldCampo5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtOldCampo6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jpOldLayout.setVerticalGroup(
            jpOldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpOldLayout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(lbOldNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpOldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbOldCampo1)
                    .addComponent(txtOldCampo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpOldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbOldCampo2)
                    .addComponent(txtOldCampo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpOldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbOldCampo3)
                    .addComponent(txtOldCampo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpOldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbOldCampo4)
                    .addComponent(txtOldCampo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpOldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbOldCampo5)
                    .addComponent(txtOldCampo5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpOldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbOldCampo6)
                    .addComponent(txtOldCampo6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        jpNew.setBackground(new java.awt.Color(204, 204, 204));

        lbNewCampo1.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        lbNewCampo1.setText("campo1:");

        lbNewCampo2.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        lbNewCampo2.setText("campo2:");

        lbNewCampo3.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        lbNewCampo3.setText("campo3:");

        lbNewCampo4.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        lbNewCampo4.setText("campo4:");

        lbNewCampo5.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        lbNewCampo5.setText("campo5:");

        lbNewCampo6.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        lbNewCampo6.setText("campo6:");

        lbNewNombre.setFont(new java.awt.Font("sansserif", 3, 15)); // NOI18N
        lbNewNombre.setText("Nombre id");

        javax.swing.GroupLayout jpNewLayout = new javax.swing.GroupLayout(jpNew);
        jpNew.setLayout(jpNewLayout);
        jpNewLayout.setHorizontalGroup(
            jpNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpNewLayout.createSequentialGroup()
                .addGroup(jpNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpNewLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(lbNewNombre))
                    .addGroup(jpNewLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jpNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbNewCampo2)
                            .addComponent(lbNewCampo1)
                            .addComponent(lbNewCampo3)
                            .addComponent(lbNewCampo4)
                            .addComponent(lbNewCampo5)
                            .addComponent(lbNewCampo6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNewCampo2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNewCampo1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNewCampo3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNewCampo4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNewCampo5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNewCampo6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jpNewLayout.setVerticalGroup(
            jpNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpNewLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lbNewNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNewCampo1)
                    .addComponent(txtNewCampo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNewCampo2)
                    .addComponent(txtNewCampo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNewCampo3)
                    .addComponent(txtNewCampo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNewCampo4)
                    .addComponent(txtNewCampo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNewCampo5)
                    .addComponent(txtNewCampo5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNewCampo6)
                    .addComponent(txtNewCampo6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btBuscar.setText("Buscar");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("sansserif", 3, 13)); // NOI18N
        jLabel1.setText("OLD");

        jLabel2.setFont(new java.awt.Font("sansserif", 3, 13)); // NOI18N
        jLabel2.setText("NEW");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jpOld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(jpNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jLabel1)
                        .addGap(255, 255, 255)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(lbEditar)))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                            .addComponent(btBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lbEditar)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btActualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscar))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpNew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpOld, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(78, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btActualizarActionPerformed
        // TODO add your handling code here:
        
        if(nombre.equalsIgnoreCase("pookemon")){
            if(pookemonBuscado!=null){
                try{
                pookemonBuscado.getEstadisticaPookemon().setVida(Integer.parseInt(txtNewCampo1.getText()));
                pookemonBuscado.getEstadisticaPookemon().setAtaqueFisico(Integer.parseInt(txtNewCampo2.getText()));
                pookemonBuscado.getEstadisticaPookemon().setDefensaFisica(Integer.parseInt(txtNewCampo3.getText()));
                pookemonBuscado.getEstadisticaPookemon().setAtaqueEspecial(Integer.parseInt(txtNewCampo4.getText()));
                pookemonBuscado.getEstadisticaPookemon().setDefensaEspecial(Integer.parseInt(txtNewCampo5.getText()));
                pookemonBuscado.getEstadisticaPookemon().setVelocidad(Integer.parseInt(txtNewCampo6.getText()));
                JOptionPane.showMessageDialog(this, "Pookemon actualizado exitosamente");   
                } catch(NumberFormatException ex){
                JOptionPane.showMessageDialog(this, "Datos mal digitados");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Pookemon no encontrado");
            }
        } else {
            if(movimientoBuscado!=null){
                try{
                    movimientoBuscado.setDescripcionMovimiento(txtNewCampo1.getText());
                    movimientoBuscado.setPotencia(Integer.parseInt(txtNewCampo2.getText()));
                    movimientoBuscado.setPrecision(Integer.parseInt(txtNewCampo3.getText()));
                    movimientoBuscado.setCantidadPP(Integer.parseInt(txtNewCampo4.getText()));
                    
                    
                    JOptionPane.showMessageDialog(this, "Movimiento actualizado exitosamente");  
                } catch(NumberFormatException ex){
                    JOptionPane.showMessageDialog(this, "Datos mal digitados");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Movimiento no encontrado");
            }
        }


    }//GEN-LAST:event_btActualizarActionPerformed

    private void txtOldCampo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOldCampo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOldCampo3ActionPerformed

    private void txtOldCampo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOldCampo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOldCampo1ActionPerformed

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        // TODO add your handling code here:
        nombreBuscado = txtBuscar.getText();
        if(nombre.equalsIgnoreCase("pookemon")){
            pookemonBuscado = torneo.buscarPokemonPorNombre(nombreBuscado);
            if(pookemonBuscado!=null){
                lbOldNombre.setText(nombreBuscado);
                lbNewNombre.setText(nombreBuscado);
                txtOldCampo1.setText(""+pookemonBuscado.getEstadisticaPookemon().getVida());
                txtOldCampo2.setText(""+pookemonBuscado.getEstadisticaPookemon().getAtaqueFisico());
                txtOldCampo3.setText(""+pookemonBuscado.getEstadisticaPookemon().getDefensaFisica());
                txtOldCampo4.setText(""+pookemonBuscado.getEstadisticaPookemon().getAtaqueEspecial());
                txtOldCampo5.setText(""+pookemonBuscado.getEstadisticaPookemon().getDefensaEspecial());
                txtOldCampo6.setText(""+pookemonBuscado.getEstadisticaPookemon().getVelocidad());
            } else {
                JOptionPane.showMessageDialog(this, "Pookemon no encontrado");
            }
        } else {
            movimientoBuscado = torneo.buscarMovimientoPorNombre(nombreBuscado);
            if(movimientoBuscado!=null){
                lbOldNombre.setText(nombreBuscado);
                lbNewNombre.setText(nombreBuscado);  
                txtOldCampo1.setText(movimientoBuscado.getDescripcionMovimiento());
                txtOldCampo2.setText(""+movimientoBuscado.getPotencia());
                txtOldCampo3.setText(""+movimientoBuscado.getPrecision());
                txtOldCampo4.setText(""+movimientoBuscado.getCantidadPP());
            } else {
                JOptionPane.showMessageDialog(this, "Movimiento no encontrado");
            }
        }
        
        
    }//GEN-LAST:event_btBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btActualizar;
    private javax.swing.JButton btBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jpNew;
    private javax.swing.JPanel jpOld;
    private javax.swing.JLabel lbEditar;
    private javax.swing.JLabel lbNewCampo1;
    private javax.swing.JLabel lbNewCampo2;
    private javax.swing.JLabel lbNewCampo3;
    private javax.swing.JLabel lbNewCampo4;
    private javax.swing.JLabel lbNewCampo5;
    private javax.swing.JLabel lbNewCampo6;
    private javax.swing.JLabel lbNewNombre;
    private javax.swing.JLabel lbOldCampo1;
    private javax.swing.JLabel lbOldCampo2;
    private javax.swing.JLabel lbOldCampo3;
    private javax.swing.JLabel lbOldCampo4;
    private javax.swing.JLabel lbOldCampo5;
    private javax.swing.JLabel lbOldCampo6;
    private javax.swing.JLabel lbOldNombre;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtNewCampo1;
    private javax.swing.JTextField txtNewCampo2;
    private javax.swing.JTextField txtNewCampo3;
    private javax.swing.JTextField txtNewCampo4;
    private javax.swing.JTextField txtNewCampo5;
    private javax.swing.JTextField txtNewCampo6;
    private javax.swing.JTextField txtOldCampo1;
    private javax.swing.JTextField txtOldCampo2;
    private javax.swing.JTextField txtOldCampo3;
    private javax.swing.JTextField txtOldCampo4;
    private javax.swing.JTextField txtOldCampo5;
    private javax.swing.JTextField txtOldCampo6;
    // End of variables declaration//GEN-END:variables

    
}
