/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main.java.com.pml.appPookemon.gui.admin;

import main.java.com.pml.appPookemon.gui.MainFrame;
import main.java.com.pml.appPookemon.gui.config.StandarPanel;

/**
 *
 * @author eddie
 */
public class GestionPanel extends StandarPanel {

    /**
     * Creates new form GestionPanel
     */
    public GestionPanel(MainFrame mainFrame) {    
        super(mainFrame);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings(value = "unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btAgrPookemon = new javax.swing.JButton();
        btEdiPookemon = new javax.swing.JButton();
        btEliPookemon = new javax.swing.JButton();
        btAgrMovimiento = new javax.swing.JButton();
        btEdiMovimiento = new javax.swing.JButton();
        btEliMovimiento = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel1.setText("Gestión del Torneo");

        btAgrPookemon.setText("Agregar Pookemon");
        btAgrPookemon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAgrPookemonActionPerformed(evt);
            }
        });

        btEdiPookemon.setText("Editar Pookemon");
        btEdiPookemon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEdiPookemonActionPerformed(evt);
            }
        });

        btEliPookemon.setText("Eliminar Pookemon");
        btEliPookemon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEliPookemonActionPerformed(evt);
            }
        });

        btAgrMovimiento.setText("Agregar Movimiento");
        btAgrMovimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAgrMovimientoActionPerformed(evt);
            }
        });

        btEdiMovimiento.setText("Editar Movimiento");
        btEdiMovimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEdiMovimientoActionPerformed(evt);
            }
        });

        btEliMovimiento.setText("Eliminar Movimiento");
        btEliMovimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEliMovimientoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btEdiPookemon, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btAgrPookemon, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btEliPookemon, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btEdiMovimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btAgrMovimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btEliMovimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(161, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel1)
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAgrPookemon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAgrMovimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btEdiPookemon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btEdiMovimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btEliMovimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btEliPookemon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(123, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btAgrPookemonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAgrPookemonActionPerformed
        super.getMainFrame().switchToAgregarPanel("POOKEMON");
        System.out.println(""+super.getMainFrame().getController().getPookemones().toString());
    }//GEN-LAST:event_btAgrPookemonActionPerformed

    private void btAgrMovimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAgrMovimientoActionPerformed
        super.getMainFrame().switchToAgregarPanel("MOVIMIENTO");
        System.out.println(""+super.getMainFrame().getController().getMovimientos().toString());
    }//GEN-LAST:event_btAgrMovimientoActionPerformed

    private void btEdiPookemonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEdiPookemonActionPerformed
        super.getMainFrame().switchToEditarPanel("POOKEMON");
    }//GEN-LAST:event_btEdiPookemonActionPerformed

    private void btEdiMovimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEdiMovimientoActionPerformed
        super.getMainFrame().switchToEditarPanel("MOVIMIENTO");
    }//GEN-LAST:event_btEdiMovimientoActionPerformed

    private void btEliPookemonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEliPookemonActionPerformed
        super.getMainFrame().switchToEliminarPanel("POOKEMON");
    }//GEN-LAST:event_btEliPookemonActionPerformed

    private void btEliMovimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEliMovimientoActionPerformed
        super.getMainFrame().switchToEliminarPanel("MOVIMIENTO");
    }//GEN-LAST:event_btEliMovimientoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAgrMovimiento;
    private javax.swing.JButton btAgrPookemon;
    private javax.swing.JButton btEdiMovimiento;
    private javax.swing.JButton btEdiPookemon;
    private javax.swing.JButton btEliMovimiento;
    private javax.swing.JButton btEliPookemon;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
