/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main.java.com.pml.appPookemon.gui.admin;

import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import main.java.com.pml.appPookemon.datos.conf_arena.controller.ArenaController;
import main.java.com.pml.appPookemon.datos.conf_arena.model.ArenaConf;
import main.java.com.pml.appPookemon.datos.pookemon.model.Movimiento;
import main.java.com.pml.appPookemon.datos.pookemon.model.Pookemon;
import main.java.com.pml.appPookemon.gui.MainFrame;
import main.java.com.pml.appPookemon.gui.config.StandarPanel;

/**
 *
 * @author eddie
 */
public class ListarPanel extends StandarPanel {

    
    public ListarPanel(MainFrame mainFrame) {
        super(mainFrame);
        initComponents();
    }
    
    public void showTables(){
        ArenaController a = new ArenaController();
        showPookemonTable(a);
        showMovimientoTable(a);
    }
    
    private void showPookemonTable(ArenaController a){
        DefaultTableModel modelPookemon = (DefaultTableModel) jtPookemones.getModel();
        modelPookemon.setRowCount(0);
        String[] daticos = new String[3];

        for (Pookemon p : a.getPookemones()) {        
            daticos[0] = String.valueOf(p.getIdPookemon());
            daticos[1] = p.getNombrePookemon();
            daticos[2] = p.getElementoPookemon();
            modelPookemon.addRow(daticos);
        }
    }
    
    private void showMovimientoTable(ArenaController a){
        DefaultTableModel modelMovimiento = (DefaultTableModel) jtMovimientos.getModel();
        modelMovimiento.setRowCount(0);
        String[] daticos = new String[4];

        for (Movimiento m : a.getMovimientos()) {        
            daticos[0] = String.valueOf(m.getIdMovimiento());
            daticos[1] = m.getNombreMovimiento();
            daticos[2] = m.getElemento();
            daticos[3] = m.getTipoMovimiento();
            modelMovimiento.addRow(daticos);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jtPookemones = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtMovimientos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jtPookemones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IdPookemon", "Nombre", "Elemento"
            }
        ));
        jScrollPane3.setViewportView(jtPookemones);

        jtMovimientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IdMovimiento", "Nombre", "Elemento", "Tipo"
            }
        ));
        jScrollPane2.setViewportView(jtMovimientos);

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setText("Listado de Pookemones: ");

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel4.setText("Listado de Movimientos: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jtMovimientos;
    private javax.swing.JTable jtPookemones;
    // End of variables declaration//GEN-END:variables
}
