/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main.java.com.pml.appPookemon.gui.batalla;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import main.java.com.pml.appPookemon.datos.pookemon.model.Pookemon;
import main.java.com.pml.appPookemon.datos.registro.model.Entrenador;
import main.java.com.pml.appPookemon.datos.conf_arena.controller.BatallaController;

/**
 *
 * @author feder
 */
public class BatallaCambio extends javax.swing.JFrame {
    private BatallaPanel bp;
    private int idPookemon;
    private int turno;
    private Pookemon pk1;
    private Pookemon pk2;
    private BatallaController controlador;
    private boolean cambioForzado;
    private int jugador;

    public BatallaCambio(BatallaController controlador) {
        idPookemon = -1;
        this.controlador = controlador;
        cambioForzado = false;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btPookemon1 = new javax.swing.JButton();
        btPookemon2 = new javax.swing.JButton();
        jVida1 = new javax.swing.JLabel();
        jVida2 = new javax.swing.JLabel();
        btCambiar = new javax.swing.JButton();
        lbTexto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        btPookemon1.setText("Pookemon1");
        btPookemon1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPookemon1ActionPerformed(evt);
            }
        });

        btPookemon2.setText("Pookemon2");
        btPookemon2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPookemon2ActionPerformed(evt);
            }
        });

        jVida1.setText("jLabel1");

        jVida2.setText("jLabel1");

        btCambiar.setText("Cambiar");
        btCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCambiarActionPerformed(evt);
            }
        });

        lbTexto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jVida1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jVida2)
                .addGap(111, 111, 111))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(btCambiar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(btPookemon1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(btPookemon2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(72, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTexto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lbTexto)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btPookemon1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(btPookemon2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jVida1)
                    .addComponent(jVida2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addComponent(btCambiar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCambiarActionPerformed
        turno = bp.getTurnoJugador();
        controlador.setAccionEntrenador(turno, "CAMBIO", idPookemon);
        if(idPookemon == -1){
            JOptionPane.showMessageDialog(this, "Por favor, seleccione un pookemon");
        }else{
            if(cambioForzado == false){
            if(turno == 1){
                bp.pasarJugador();
            }else{
                bp.pasarJugador();
                bp.realizarTurno();
                bp.configurarImagenes();
                bp.configurarTextos();
                bp.actualizarVidaVisual();
            }
            bp.configurarFlecha();
            }else{
                if(jugador == 1){
                    controlador.setAccionEntrenador(1, "CAMBIO", idPookemon);
                    controlador.setAccionEntrenador(2, "DEFENDER", idPookemon);
                }else{
                    controlador.setAccionEntrenador(2, "CAMBIO", idPookemon);
                    controlador.setAccionEntrenador(1, "DEFENDER", idPookemon);
                }
                bp.realizarTurno();
                bp.configurarImagenes();
                bp.configurarTextos();
                bp.actualizarVidaVisual();
                bp.configurarFlecha();
            }
            dispose();
        }
        
    }//GEN-LAST:event_btCambiarActionPerformed

    private void btPookemon1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPookemon1ActionPerformed
        idPookemon = pk1.getIdPookemon();
    }//GEN-LAST:event_btPookemon1ActionPerformed

    private void btPookemon2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPookemon2ActionPerformed
        idPookemon = pk2.getIdPookemon();
    }//GEN-LAST:event_btPookemon2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BatallaCambio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BatallaCambio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BatallaCambio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BatallaCambio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
            }
        });
    }
    
    public void configurar(int jugador){
        this.jugador = jugador;
        Entrenador e = null;
        
        
        e = controlador.getEntrenador(this.jugador);
       
        pk1 = e.obtenerPookemonesDiferentesActual().get(0);
        pk2 = e.obtenerPookemonesDiferentesActual().get(1);
        
        //cambiar entrenador1 por determinarTurno;
        btPookemon1.setText(pk1.getNombrePookemon());
        btPookemon2.setText(pk2.getNombrePookemon());
        
        jVida1.setText("HP " + pk1.getEstadisticaPookemon().getVida());
        jVida2.setText("HP " + pk2.getEstadisticaPookemon().getVida());
        
        if(cambioForzado){
            lbTexto.setText("Entrenador " + e.getNombreEntrenador() + ", " + e.getPookemonActual().getNombrePookemon() + " ha quedado fuera de combate, cambialo");
        }
    }
    
    public void setPanelBatalla(BatallaPanel bp){
        this.bp = bp;
    }

    public void setCambioForzado(boolean cambioForzado) {
        this.cambioForzado = cambioForzado;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCambiar;
    private javax.swing.JButton btPookemon1;
    private javax.swing.JButton btPookemon2;
    private javax.swing.JLabel jVida1;
    private javax.swing.JLabel jVida2;
    private javax.swing.JLabel lbTexto;
    // End of variables declaration//GEN-END:variables
}
