/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main.java.com.pml.appPookemon.gui.batalla;

import javax.swing.JOptionPane;
import main.java.com.pml.appPookemon.datos.pookemon.model.Movimiento;
import main.java.com.pml.appPookemon.datos.registro.model.Entrenador;
import main.java.com.pml.appPookemon.datos.torneo.controller.BatallaController;

/**
 *
 * @author feder
 */
public class BatallaAtaque extends javax.swing.JFrame {
    private BatallaPanel bp;
    private BatallaController controlador;
    private Movimiento ataque1;
    private Movimiento ataque2;
    private Movimiento ataque3;
    private Movimiento ataque4;
    private int idMovimiento;
    /**
     * Creates new form BatallaAtaque
     * @param controlador
     */
    public BatallaAtaque(BatallaController controlador) {
        this.controlador = controlador;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btAtaque2 = new javax.swing.JButton();
        btAtaque3 = new javax.swing.JButton();
        btAtaque1 = new javax.swing.JButton();
        btRealizar = new javax.swing.JButton();
        jPP1 = new javax.swing.JLabel();
        jPP2 = new javax.swing.JLabel();
        jPP3 = new javax.swing.JLabel();
        btAtaque4 = new javax.swing.JButton();
        jPP4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        btAtaque2.setText("Ataque2");
        btAtaque2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtaque2ActionPerformed(evt);
            }
        });

        btAtaque3.setText("Ataque1");
        btAtaque3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtaque3ActionPerformed(evt);
            }
        });

        btAtaque1.setText("Ataque1");
        btAtaque1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtaque1ActionPerformed(evt);
            }
        });

        btRealizar.setText("Realizar");
        btRealizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRealizarActionPerformed(evt);
            }
        });

        jPP1.setText("jLabel1");

        jPP2.setText("jLabel1");

        jPP3.setText("jLabel1");

        btAtaque4.setText("Ataque1");
        btAtaque4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtaque4ActionPerformed(evt);
            }
        });

        jPP4.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(btAtaque1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btAtaque2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btAtaque3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addComponent(jPP3)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btAtaque4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addComponent(jPP4))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jPP1)
                        .addGap(103, 103, 103)
                        .addComponent(jPP2)))
                .addContainerGap(99, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btRealizar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(155, 155, 155))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btAtaque2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAtaque1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPP1)
                    .addComponent(jPP2))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btAtaque3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPP3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btAtaque4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPP4)))
                .addGap(71, 71, 71)
                .addComponent(btRealizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btAtaque2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtaque2ActionPerformed
        idMovimiento = ataque2.getIdMovimiento();
        System.out.println("Id del movimiento " + ataque2.getNombreMovimiento() +": " + idMovimiento);
    }//GEN-LAST:event_btAtaque2ActionPerformed

    private void btAtaque3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtaque3ActionPerformed
        idMovimiento = ataque3.getIdMovimiento();
        System.out.println("Id del movimiento " + ataque3.getNombreMovimiento() +": " + idMovimiento);
    }//GEN-LAST:event_btAtaque3ActionPerformed

    private void btAtaque1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtaque1ActionPerformed
        idMovimiento = ataque1.getIdMovimiento();
        System.out.println("Id del movimiento " + ataque1.getNombreMovimiento() +": " + idMovimiento);
    }//GEN-LAST:event_btAtaque1ActionPerformed

    private void btRealizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRealizarActionPerformed
        
        try{
        int turno = bp.getTurnoJugador();
        controlador.setAccionEntrenador(turno, "ATACAR", idMovimiento);
        if(turno == 1){
            bp.pasarJugador();
        }else{
            bp.pasarJugador();
            bp.realizarTurno();
            bp.configurarImagenes();
            bp.configurarTextos();
            bp.actualizarVidaVisual();
        }
        bp.configurarFlecha();
        } catch(NullPointerException ex){
            JOptionPane.showMessageDialog(this, "No se seleccionó ningún movimiento");
        }
        dispose();
    }//GEN-LAST:event_btRealizarActionPerformed

    private void btAtaque4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtaque4ActionPerformed
        idMovimiento = ataque4.getIdMovimiento();
        System.out.println("Id del movimiento " + ataque4.getNombreMovimiento() +": " + idMovimiento);
    }//GEN-LAST:event_btAtaque4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BatallaAtaque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BatallaAtaque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BatallaAtaque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BatallaAtaque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }
    
    public void configurar(int jugador){
        
        Entrenador e = null;
        if(jugador == 1){
            e = controlador.getEntrenador1();
        }else{
            e = controlador.getEntrenador2();
        }
        
        //cambiar entrenador1 por determinarTurno;
        ataque1 = e.getPookemonActual().getMovimientos().get(0);
        ataque2 = e.getPookemonActual().getMovimientos().get(1);
        ataque3 = e.getPookemonActual().getMovimientos().get(2);
        ataque4 = e.getPookemonActual().getMovimientos().get(3);
        
        btAtaque1.setText(ataque1.getNombreMovimiento());
        btAtaque2.setText(ataque2.getNombreMovimiento());
        btAtaque3.setText(ataque3.getNombreMovimiento());
        btAtaque4.setText(ataque4.getNombreMovimiento());
        
        jPP1.setText("PP " + ataque1.getCantidadPP() + "/" + ataque1.getCantidadMaximaPPs());
        jPP2.setText("PP " + ataque2.getCantidadPP() + "/" + ataque2.getCantidadMaximaPPs());
        jPP3.setText("PP " + ataque3.getCantidadPP() + "/" + ataque3.getCantidadMaximaPPs());
        jPP4.setText("PP " + ataque4.getCantidadPP() + "/" + ataque4.getCantidadMaximaPPs());
    }
    
    public void setPanelBatalla(BatallaPanel bp){
        this.bp = bp;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAtaque1;
    private javax.swing.JButton btAtaque2;
    private javax.swing.JButton btAtaque3;
    private javax.swing.JButton btAtaque4;
    private javax.swing.JButton btRealizar;
    private javax.swing.JLabel jPP1;
    private javax.swing.JLabel jPP2;
    private javax.swing.JLabel jPP3;
    private javax.swing.JLabel jPP4;
    // End of variables declaration//GEN-END:variables
}
