package main.java.com.pml.appPookemon.gui.batalla;

import java.net.URL;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.ImageIcon;
import main.java.com.pml.appPookemon.controller.BatallaControlador;
import main.java.com.pml.appPookemon.datos.pookemon.model.Movimiento;
import main.java.com.pml.appPookemon.datos.pookemon.model.MovimientoEspecial;
import main.java.com.pml.appPookemon.datos.pookemon.model.MovimientoFisico;
import main.java.com.pml.appPookemon.datos.pookemon.model.Pookemon;
import main.java.com.pml.appPookemon.datos.registro.model.Entrenador;
import main.java.com.pml.appPookemon.gui.MainFrame;
import main.java.com.pml.appPookemon.gui.config.StandarPanel;
import main.java.com.pml.appPookemon.datos.torneo.*;

/**
 *
 * @author feder
 */
public class BatallaPanel extends StandarPanel {
    private Entrenador j1;
    private Entrenador j2;
    private Entrenador[] entrenadores;
    private Batalla batalla;
    private BatallaControlador controlador;
    /**
     * Creates new form BatallaPrincipal
     */
    public BatallaPanel(MainFrame mainFrame) {
        super(mainFrame);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_nombrePookemon_1 = new javax.swing.JLabel();
        btAtacar = new javax.swing.JButton();
        btDefender = new javax.swing.JButton();
        btCambiar = new javax.swing.JButton();
        btObjeto = new javax.swing.JButton();
        lb_nombrePookemon_2 = new javax.swing.JLabel();
        lbVidaPookemon1 = new javax.swing.JLabel();
        lbVidaPookemon2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaLog = new javax.swing.JTextArea();
        imgPookemon1 = new javax.swing.JLabel();
        pbVida1 = new javax.swing.JProgressBar();
        pbVida2 = new javax.swing.JProgressBar();
        imgPookemon2 = new javax.swing.JLabel();

        lb_nombrePookemon_1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lb_nombrePookemon_1.setText("Nombre Pookemon");
        lb_nombrePookemon_1.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                lb_nombrePookemon_1ComponentAdded(evt);
            }
        });
        lb_nombrePookemon_1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lb_nombrePookemon_1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        lb_nombrePookemon_1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                lb_nombrePookemon_1ComponentShown(evt);
            }
        });

        btAtacar.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btAtacar.setText("ATACAR");
        btAtacar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btDefender.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btDefender.setText("DEFENDER");
        btDefender.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btDefender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDefenderActionPerformed(evt);
            }
        });

        btCambiar.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btCambiar.setText("CAMBIAR");
        btCambiar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCambiarActionPerformed(evt);
            }
        });

        btObjeto.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btObjeto.setText("OBJETOS");
        btObjeto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btObjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btObjetoActionPerformed(evt);
            }
        });

        lb_nombrePookemon_2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lb_nombrePookemon_2.setText("Nombre Pookemon");

        lbVidaPookemon1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lbVidaPookemon1.setText("HP");

        lbVidaPookemon2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lbVidaPookemon2.setText("HP");

        txtAreaLog.setColumns(20);
        txtAreaLog.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtAreaLog.setRows(5);
        jScrollPane1.setViewportView(txtAreaLog);

        imgPookemon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/img/EleLucha.png"))); // NOI18N

        pbVida1.setValue(50);

        imgPookemon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/img/EleAcero.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btAtacar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btCambiar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btDefender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lb_nombrePookemon_1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbVidaPookemon1)
                        .addComponent(pbVida1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(198, 198, 198)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbVidaPookemon2)
                        .addGap(200, 200, 200))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pbVida2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_nombrePookemon_2))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(imgPookemon1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(imgPookemon2)
                .addGap(151, 151, 151))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_nombrePookemon_1)
                    .addComponent(lb_nombrePookemon_2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(pbVida1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(imgPookemon1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbVidaPookemon2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbVidaPookemon1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pbVida2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(imgPookemon2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btAtacar)
                            .addComponent(btDefender))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btCambiar)
                            .addComponent(btObjeto))
                        .addGap(67, 67, 67))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btDefenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDefenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btDefenderActionPerformed

    private void btCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCambiarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btCambiarActionPerformed

    private void btObjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btObjetoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btObjetoActionPerformed

    private void lb_nombrePookemon_1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_lb_nombrePookemon_1ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_lb_nombrePookemon_1ComponentShown

    private void lb_nombrePookemon_1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lb_nombrePookemon_1AncestorAdded

    }//GEN-LAST:event_lb_nombrePookemon_1AncestorAdded

    private void lb_nombrePookemon_1ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_lb_nombrePookemon_1ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_lb_nombrePookemon_1ComponentAdded

    
    // Método para cambiar la imagen del personaje 
    // FALTA TERMINAR 
    public void cambiarImagenPersonaje(String rutaImagen) {
        // Cargar la imagen desde la ruta especificada
        ImageIcon icon = new ImageIcon(getClass().getResource(rutaImagen));
        // Asignar la imagen al JLabel
        imgPookemon1.setIcon(icon);
    }
    
    public void configurar(){
       entrenadores = super.getMainFrame().getController().batallaActual();
       j1 = entrenadores[0];
       j2 = entrenadores[1];
       batalla = new Batalla(0, j1, j2, pookemonesYVainasFalsasloljaja());
       batalla.generarMazo();
       controlador = new BatallaControlador(batalla);
       configurarTextos();
       configurarImagenes();
    }
    
    public void configurarTextos(){
        Pookemon j1Pookemon = controlador.getEntrenador1().getPookemonActual();
        Pookemon j2Pookemon = controlador.getEntrenador2().getPookemonActual();
        int vidaPookemon1 = j1Pookemon.getEstadisticaPookemon().getVida();
        int vidaPookemon2 = j2Pookemon.getEstadisticaPookemon().getVida();
       
        lb_nombrePookemon_1.setText(j1Pookemon.getNombrePookemon());
        lb_nombrePookemon_2.setText(j2Pookemon.getNombrePookemon());
        lbVidaPookemon1.setText("HP  " + vidaPookemon1);
        lbVidaPookemon2.setText("HP  " + vidaPookemon2);
        pbVida1.setMaximum(vidaPookemon1);
        pbVida2.setMaximum(vidaPookemon2);
        pbVida1.setValue(vidaPookemon1);
        pbVida2.setValue(vidaPookemon2);
    }
    
    public void configurarImagenes(){
        String nombre1 = controlador.getEntrenador1().getPookemonActual().getNombrePookemon().toLowerCase();
        String nombre2 = controlador.getEntrenador2().getPookemonActual().getNombrePookemon().toLowerCase();
        URL imagen1 = getClass().getResource("/img/SpritesPookemon/"+nombre1+".gif");
        URL imagen2 = getClass().getResource("/img/SpritesPookemon/"+nombre2+".gif");
        ImageIcon img1 = new ImageIcon(imagen1);
        ImageIcon img2 = new ImageIcon(imagen2);
        imgPookemon1.setIcon(img1);
        imgPookemon2.setIcon(img2);
    }
           /*
       *******************************************************************
       *     FUNCIÓN FALSA QUE AGREGA LOS POOKEMONES YA CREADOS          *
       *     XDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD          *
       *******************************************************************
       */
    public ArrayList<Pookemon> pookemonesYVainasFalsasloljaja(){
        Pookemon Roserade = new Pookemon(407, "Roserade", "planta");
        Roserade.inicializarEstadistica(60, 70, 65, 125, 105, 90);

        Pookemon Venusaur = new Pookemon(3, "Venusaur", "planta");
        Venusaur.inicializarEstadistica(80, 82, 83, 100, 100, 80);

        Pookemon Typhlosion = new Pookemon(157, "Typhlosion", "fuego");
        Typhlosion.inicializarEstadistica(78, 84, 78, 109, 85, 100);

        Pookemon Gyarados = new Pookemon(130, "Gyarados", "agua");
        Gyarados.inicializarEstadistica(95, 125, 79, 60, 100, 81);

        Pookemon Milotic = new Pookemon(350, "Milotic", "agua");
        Milotic.inicializarEstadistica(95, 60, 79, 100, 125, 81);

        Pookemon Greninja = new Pookemon(658, "Greninja", "agua");
        Greninja.inicializarEstadistica(72, 95, 67, 103, 71, 122);

        Pookemon Raichu = new Pookemon(26, "Raichu", "electrico");
        Raichu.inicializarEstadistica(60, 90, 55, 90, 80, 110);

        Pookemon Nidoking = new Pookemon(34, "Nidoking", "veneno");
        Nidoking.inicializarEstadistica(81, 102, 77, 85, 75, 85);

        Pookemon Alakazam = new Pookemon(65, "Alakazam", "psiquico");
        Alakazam.inicializarEstadistica(55, 50, 45, 135, 95, 120);

        Pookemon Hypno = new Pookemon(97, "Hypno", "psiquico");
        Hypno.inicializarEstadistica(85, 73, 70, 73, 115, 67);
        
        Movimiento Lanzallamas = new MovimientoEspecial(1, "Lanzallamas", 90, 100, 10, "fuego", null);
        Movimiento PunoFuego = new MovimientoFisico(2, "Puño Fuego",75, 100, 15, "fuego", null);
        Movimiento Llamarada = new MovimientoEspecial(3, "Llamarada", 110, 85, 5, "fuego", null);
         
        Roserade.setMovimientos(new ArrayList<>(Arrays.asList(Lanzallamas,PunoFuego,Llamarada)));
        return new ArrayList<>(Arrays.asList(Roserade));

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAtacar;
    private javax.swing.JButton btCambiar;
    private javax.swing.JButton btDefender;
    private javax.swing.JButton btObjeto;
    private javax.swing.JLabel imgPookemon1;
    private javax.swing.JLabel imgPookemon2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbVidaPookemon1;
    private javax.swing.JLabel lbVidaPookemon2;
    private javax.swing.JLabel lb_nombrePookemon_1;
    private javax.swing.JLabel lb_nombrePookemon_2;
    private javax.swing.JProgressBar pbVida1;
    private javax.swing.JProgressBar pbVida2;
    private javax.swing.JTextArea txtAreaLog;
    // End of variables declaration//GEN-END:variables
}
